controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

product_sort:
    path: /products/sort
    controller: App\Controller\ProductController::sortProducts
    methods: ['GET']